import type { Metadata } from "next";
import "./globals.css";
import { PageLayout } from "@/widgets/layout/ui/page-layout";
import { QueryProvider } from "@/providers/QueryProvider";
import { Toaster } from "@/shared/ui/sonner";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../public/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <QueryProvider>
          <PageLayout>{children}</PageLayout>
          <Toaster richColors position="top-right" />
        </QueryProvider>
      </body>
    </html>
  );
}
