/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Retrieve all projects.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project list returned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectListResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create project
         * @description Create a new project.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Project created successfully. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project details
         * @description Retrieve a specific project and its file list by project ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project ID
                     * @example clq1234abcd
                     */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project returned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDetailsResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectNotFoundError"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete project
         * @description Delete a specific project by project ID. All files in the project are deleted as well.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project ID
                     * @example clq1234abcd
                     */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Project and all related files (all versions) deleted successfully."
                         *     }
                         */
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectNotFoundError"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate presigned URL
         * @description Generate a presigned URL for file upload. Clients can use this URL to upload files directly to OCI.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project ID
                     * @example clq1234abcd
                     */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PresignRequest"];
                };
            };
            responses: {
                /** @description Presigned URL generated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresignResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description File size exceeded or storage quota exceeded */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm upload
         * @description Call this after direct upload to OCI to create a file record in the database. For image files, variants can be provided to request transformation.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project ID
                     * @example clq1234abcd
                     */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description File record created successfully. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Image upload and processing complete",
                         *       "file": {
                         *         "id": "file5678efgh",
                         *         "name": "image.jpg",
                         *         "mimeType": "image/jpeg",
                         *         "isImage": true,
                         *         "size": 102400,
                         *         "url": null,
                         *         "variants": [
                         *           {
                         *             "url": "https://objectstorage.ap-seoul-1.oraclecloud.com/...",
                         *             "width": 1920,
                         *             "height": 1080,
                         *             "size": 102400,
                         *             "format": "jpeg",
                         *             "label": "1920x1080"
                         *           }
                         *         ],
                         *         "createdAt": "2023-01-01T00:00:00.000Z",
                         *         "updatedAt": "2023-01-01T00:00:00.000Z",
                         *         "projectId": "clq1234abcd"
                         *       },
                         *       "variants": [
                         *         {
                         *           "url": "https://objectstorage.ap-seoul-1.oraclecloud.com/...",
                         *           "width": 1920,
                         *           "height": 1080,
                         *           "size": 102400,
                         *           "format": "jpeg",
                         *           "label": "1920x1080"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["ConfirmResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description File not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileNotFoundError"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete file
         * @description Delete a file with the specified ID and all related versions (including OCI storage).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project ID
                     * @example clq1234abcd
                     */
                    projectId: string;
                    /**
                     * @description File ID
                     * @example file5678efgh
                     */
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "File deleted successfully."
                         *     }
                         */
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description File not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileNotFoundError"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Error message
             * @example An error occurred while processing the request.
             */
            message: string;
            /**
             * @description Field-level validation errors
             * @example {
             *       "name": [
             *         "This field is required."
             *       ]
             *     }
             */
            errors?: {
                [key: string]: string[];
            };
        };
        UnauthorizedError: {
            /**
             * @description Error message
             * @example Authentication failed: invalid API key
             */
            message: string;
        };
        ProjectNotFoundError: {
            /**
             * @description Error message
             * @example Resource not found.
             */
            message: string;
        };
        FileNotFoundError: {
            /**
             * @description Error message
             * @example Resource not found.
             */
            message: string;
        };
        ServerError: {
            /**
             * @description Error message
             * @example A server error occurred.
             */
            message: string;
        };
        BadRequestError: {
            /**
             * @description Error message
             * @example Invalid request format.
             */
            message: string;
            /**
             * @description Field-level validation errors
             * @example {
             *       "name": [
             *         "This field is required."
             *       ]
             *     }
             */
            errors?: {
                [key: string]: string[];
            };
        };
        MessageResponse: {
            /**
             * @description Success message
             * @example Operation completed successfully.
             */
            message: string;
        };
        VariantOption: {
            /**
             * @description Image size label. Presets: source (original), max300 (longest side 300px), max800 (longest side 800px), max1920 (longest side 1920px), or custom resolution (WIDTHxHEIGHT format).
             * @example source
             */
            sizeLabel: ("source" | "max300" | "max800" | "max1920") | string;
            /**
             * @description Image format
             * @example webp
             * @enum {string}
             */
            format: "png" | "jpeg" | "avif" | "webp";
        };
        ImageVariantData: {
            /**
             * Format: uri
             * @description Image URL
             * @example https://objectstorage.ap-seoul-1.oraclecloud.com/...
             */
            url: string;
            /**
             * @description Image width (px)
             * @example 1920
             */
            width: number;
            /**
             * @description Image height (px)
             * @example 1080
             */
            height: number;
            /**
             * @description File size (bytes)
             * @example 102400
             */
            size: number;
            /**
             * @description Image format
             * @example webp
             */
            format: string;
            /**
             * @description Size label
             * @example original
             */
            label: string;
        };
        /**
         * @example {
         *       "fileName": "image.jpg",
         *       "contentType": "image/jpeg",
         *       "fileSize": 102400,
         *       "width": 421,
         *       "height": 524
         *     }
         */
        PresignRequest: {
            /**
             * @description Name of the file to upload
             * @example image.jpg
             */
            fileName: string;
            /**
             * @description MIME type of the file
             * @example image/jpeg
             */
            contentType: string;
            /**
             * @description File size (bytes)
             * @example 102400
             */
            fileSize: number;
            /**
             * @description (Image only) Original image width in pixels. Provide with height to include exact resolution in objectName; when omitted, source placeholder naming is used.
             * @example 421
             */
            width?: number;
            /**
             * @description (Image only) Original image height in pixels. Provide with width to include exact resolution in objectName; when omitted, source placeholder naming is used.
             * @example 524
             */
            height?: number;
        };
        PresignResponse: {
            /**
             * Format: uri
             * @description Presigned URL for direct upload to OCI
             * @example https://objectstorage.ap-seoul-1.oraclecloud.com/p/...
             */
            presignedUrl: string;
            /**
             * @description OCI object path. Image objects use either {fileId}-{width}x{height}-{ext}.{ext} (when width/height are provided) or {fileId}-source-{ext}.{ext} (when omitted).
             * @example clq1234abcd/file5678efgh-source-jpg.jpg
             */
            objectName: string;
            /**
             * Format: uri
             * @description Object URL after upload completion
             * @example https://objectstorage.ap-seoul-1.oraclecloud.com/n/.../o/...
             */
            objectUrl: string;
            /**
             * @description Generated file ID
             * @example file5678efgh
             */
            fileId: string;
            /**
             * Format: date-time
             * @description Presigned URL expiration time (ISO 8601)
             * @example 2023-01-01T00:15:00.000Z
             */
            expiresAt: string;
        };
        /**
         * @example {
         *       "fileId": "file5678efgh",
         *       "objectName": "clq1234abcd/file5678efgh-source-jpg.jpg",
         *       "fileName": "image.jpg",
         *       "contentType": "image/jpeg",
         *       "fileSize": 102400,
         *       "variants": [
         *         {
         *           "sizeLabel": "source",
         *           "format": "webp"
         *         },
         *         {
         *           "sizeLabel": "max800",
         *           "format": "jpeg"
         *         }
         *       ]
         *     }
         */
        ConfirmRequest: {
            /**
             * @description File ID from presign response
             * @example file5678efgh
             */
            fileId: string;
            /**
             * @description Object name from presign response
             * @example clq1234abcd/file5678efgh-source-jpg.jpg
             */
            objectName: string;
            /**
             * @description Original file name
             * @example image.jpg
             */
            fileName: string;
            /**
             * @description MIME type of the file
             * @example image/jpeg
             */
            contentType: string;
            /**
             * @description File size (bytes)
             * @example 102400
             */
            fileSize: number;
            /** @description (Image only) Array of image variant options to generate */
            variants?: components["schemas"]["VariantOption"][];
        };
        FileResponse: {
            /**
             * @description File ID
             * @example file5678efgh
             */
            id: string;
            /**
             * @description File name
             * @example image.jpg
             */
            name: string;
            /**
             * @description MIME type
             * @example image/jpeg
             */
            mimeType: string;
            /**
             * @description Whether it is an image file
             * @example true
             */
            isImage: boolean;
            /**
             * @description File size (bytes)
             * @example 102400
             */
            size: number;
            /**
             * Format: uri
             * @description URL for non-image files
             * @example null
             */
            url: string | null;
            /** @description Image variants list (image files only) */
            variants: components["schemas"]["ImageVariantData"][];
            /**
             * Format: date-time
             * @description Created at (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Updated at (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            updatedAt: string;
            /**
             * @description Project ID
             * @example clq1234abcd
             */
            projectId: string;
        };
        ConfirmResponse: {
            /**
             * @description Success message
             * @example File upload complete
             */
            message: string;
            file: components["schemas"]["FileResponse"];
            /** @description Generated image variants */
            variants?: components["schemas"]["ImageVariantData"][];
        };
        /**
         * @example {
         *       "name": "Website Assets",
         *       "description": "File collection used for the website",
         *       "storageProvider": "OCI"
         *     }
         */
        CreateProjectRequest: {
            /**
             * @description Project name (3-50 characters)
             * @example Website Assets
             */
            name: string;
            /**
             * @description Project description (max 200 characters)
             * @example File collection used for the website
             */
            description?: string;
            /**
             * @description Storage provider (default: OCI). Allowed values: OCI, R2
             * @default OCI
             * @example OCI
             * @enum {string}
             */
            storageProvider: "OCI" | "R2";
        };
        /**
         * @example {
         *       "name": "Updated Project Name",
         *       "description": "Updated project description"
         *     }
         */
        UpdateProjectRequest: {
            /**
             * @description Project name (1-50 characters)
             * @example Updated Project Name
             */
            name?: string;
            /**
             * @description Project description (max 200 characters)
             * @example Updated project description
             */
            description?: string;
        };
        ProjectResponse: {
            /**
             * @description Project ID
             * @example clq1234abcd
             */
            id: string;
            /**
             * @description Project name
             * @example Website Assets
             */
            name: string;
            /**
             * @description Project description
             * @example File collection used for the website
             */
            description: string | null;
            /**
             * @description Storage provider
             * @example OCI
             * @enum {string}
             */
            storageProvider: "OCI" | "R2";
            /**
             * Format: date-time
             * @description Created at (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Updated at (ISO 8601)
             * @example 2023-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        ProjectListItemResponse: components["schemas"]["ProjectResponse"] & {
            /**
             * @description Number of files in the project
             * @example 12
             */
            fileCount: number;
        };
        ProjectDetailsResponse: components["schemas"]["ProjectResponse"] & {
            /** @description List of files in the project */
            files: components["schemas"]["FileResponse"][];
        };
        ProjectListResponse: components["schemas"]["ProjectListItemResponse"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
